// Why: This file is imported by auth.ts which is bundled for the Convex V8 runtime.
// googleapis requires Node.js built-ins (fs, stream, etc.) that cannot be bundled
// for V8. Gmail sending is therefore delegated to email.sendResetCode, which lives
// in the "use node" email.ts file and is called via ctx.runAction at runtime.
// Convex Auth passes the action ctx as a second argument to sendVerificationRequest
// (see @convex-dev/auth signIn.js) — TypeScript accepts it despite the @auth/core
// type having a single-parameter signature (method-level bivariance).

import { Email } from "@convex-dev/auth/providers/Email";
import type { FunctionReference } from "convex/server";
import { internal } from "./_generated/api";

// Minimal action-ctx interface typed without any: Convex Auth passes the action ctx
// as the second argument to sendVerificationRequest at runtime.
type ActionCtxLike = {
  runAction(
    fn: FunctionReference<"action", "internal">,
    args: Record<string, string>,
  ): Promise<void>;
};

// Convex Auth Email provider: code is generated by Convex Auth; we only send it.
export const ResetEmail = Email({
  id: "reset-email",
  maxAge: 60 * 15, // code valid 15 min
  // ctx is optional in the declared type but always supplied by Convex Auth at runtime
  // (see signIn.js in @convex-dev/auth). Making it optional makes TypeScript accept
  // this function where only one argument is declared by @auth/core's EmailConfig.
  sendVerificationRequest: async (
    { identifier: email, token }: { identifier: string; token: string },
    ctx?: ActionCtxLike,
  ) => {
    // Dry-run guard: log when SMTP creds are absent (local dev / CI). When configured,
    // delegate to the "use node" action below (nodemailer can't run in this V8 bundle).
    if (!process.env.GMAIL_USER) {
      console.log(`[reset] (no SMTP creds) code pour ${email}: ${token}`);
      return;
    }
    if (!ctx) {
      // Should not happen: Convex Auth always passes ctx. Log and abort gracefully.
      console.error(`[reset] ctx unavailable — cannot send reset email to ${email}`);
      return;
    }
    // Delegate to the "use node" action so googleapis can access Node.js built-ins
    await ctx.runAction(internal.email.sendResetCode, { email, token });
  },
});
